url:
  rails_home: "https://www.railstutorial.org/"
  rails_book: "https://www.railstutorial.org/book"
  rails_help: "https://www.railstutorial.org/help"
  rails_news: "https://news.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  gravatar:   "https://secure.gravatar.com/avatar/"

digits:
  digit_255: 255
  digit_50: 50
  digit_6: 6
gravatar_size:
  size_100: 100


