url:
  rails_home: "https://www.railstutorial.org/"
  rails_book: "https://www.railstutorial.org/book"
  rails_help: "https://www.railstutorial.org/help"
  rails_news: "https://news.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  gravatar: "https://secure.gravatar.com/avatar/"
  gravatar_email: "http://gravatar.com/emails"
digits:
  digit_255: 255
  digit_50: 50
  digit_6: 6
gravatar_size:
  size_30: 30
  size_50: 50
  size_100: 100
time:
  expire:
    two_hrs: 2
image:
  size_5: 5
  limit_size_500: [500, 500]
  format_valid: ["image/jpeg", "image/gif", "image/png"]
  accept_image: "image/jpeg,image/gif,image/png"
content:
  character_140: 140





